pipeline {
    agent any

    stages {
        stage('ExchangeRate') {
            stages {
                stage('ExchangeRate - CI') {
                    steps {
                        sh("docker build -t registry.dev.crosstech.com.tr/exchange-rate -f Devops/Docker/Dockerfile .")
                        sh("docker push registry.dev.crosstech.com.tr/exchange-rate")
                    }
                }
                 stage('ExchangeRate - CD') {
                    steps {
                        sh("./Devops/Scripts/exchange-rate/stop.sh || true ")
                        sh("./Devops/Scripts/exchange-rate/start.sh ")
                    }
                }
            }
        }
    }
}